name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t angular-app .

      - name: Deploy Docker container
        run: |
          docker stop angular-app || true
          docker rm angular-app || true
          docker run -d -p 8080:80 --name angular-app angular-app
